# Generated by Django 2.2.7 on 2019-11-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.FloatField()),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=50)),
                ("business", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
