# Generated by Django 3.0.2 on 2020-04-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20191121_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_calculation',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_category',
            field=models.CharField(default='Purchase', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='business',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
