language: python
before_install:
- openssl aes-256-cbc -K $encrypted_d790e4e029ac_key -iv $encrypted_d790e4e029ac_iv
  -in client-secret.json.enc -out client-secret.json -d
install:
- make install
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: budget-app
  default: true
  on:
    all_branches: true
