dist: trusty
jobs:
  include:
  - stage: test
    language: python
    name: Backend Tests
    python:
    - 3.6
    - DJANGO_SETTINGS_MODULE=config.production
    install:
    - make install
    script:
    - make build
    - make test
    after_success:
      - coveralls
    cache:
      directories:
      - "$HOME/.cache/pip"
